<div class="block review-add">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('Write Your Own Review')) ?></strong>
    </div>
    <div class="block-content">
        <form action="<?= $block->getUrl('techshop_review/review/post') ?>" class="review-form" method="post" id="review-form" data-role="product-review-form">
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset review-fieldset">

                <!-- Campo Nickname -->
                <div class="field review-field-nickname required">
                    <label for="nickname_field" class="label">
                        <span><?= $block->escapeHtml(__('Nickname')) ?></span>
                    </label>
                    <div class="control">
                        <input type="text" name="nickname" id="nickname_field" class="input-text" data-validate="{required:true}" />
                    </div>
                </div>
                <div class="field review-field-text required">
                    <label for="review_comment" class="label">
                        <span><?= $block->escapeHtml(__('Comment')) ?></span>
                    </label>
                    <div class="control">
                        <textarea name="comment" id="review_comment" cols="5" rows="3" data-validate="{required:true}"></textarea>
                    </div>
                </div>
                <div class="field rating required">
                    <label for="review_rating" class="label">
                        <span><?= $block->escapeHtml(__('Rating')) ?></span>
                    </label>
                    <div class="control">
                        <div class="stars">
                            <?php for ($i = 1; $i <= 5; $i++): ?>
                                <span class="fa fa-star" data-rating="<?= $i ?>"></span>
                            <?php endfor; ?>
                        </div>
                        <input type="hidden" name="rating" id="review_rating" data-validate="{required:true}" />
                    </div>
                </div>

                <!-- Botão de envio -->
                <div class="actions-toolbar review-form-actions">
                    <div class="primary actions-primary">
                        <button type="submit" class="action submit primary">
                            <span><?= $block->escapeHtml(__('Submit Review')) ?></span>
                        </button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>

<script type="text/x-magento-init">
{
    ".stars": {
        "customStarRating": {}
    }
}
</script>

